In [ ]:
# 라이브러리(패키지)를 사용하려면 먼저 패키지를 설치해야함
# pip : 파이썬의 패키지 소프트웨어 설치 및 관리하는 패키지 관리 시스템
# 패키지 설치 방법 : pip install 패키지명

# 구글에 scikit 검색 -> install -> "pip install -U scikit-learn"복사 -> 터미널에 붙여넣기

In [3]:
# 설치한 패키지를 해당 파일에서 사용하려면
# import 패키지명 으로 패키지를 가져올 수 있음
# import 패키지명 as 별명으로 패키지 별명을 지정하여 사용할 수 있음

In [2]:
import sklearn

In [4]:
import numpy as np

In [ ]:
# dir(패키지명)으로 패키지에 포함되어 있는 내용을 확인할 수 있음

In [6]:
dir(sklearn)

['_BUILT_WITH_MESON',
 '__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_distributor_init',
 'base',
 'clone',
 'config_context',
 'exceptions',
 'externals',
 'get_config',
 'logger',
 'logging',
 'os',
 'random',
 'set_config',
 'setup_module',
 'show_versions',
 'sys',
 'utils']

In [7]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [8]:
# 패키지를 임포트하면 대부분 하위 패키지도 같이 임포트 되지만,
# 직접 명시적으로 임포트 해야하는 하위 패키지도 존재함

# 자주 사용하는 하위 패키지일 경우 직접 해당 패키지를 임포트해서 사용하기도 함

In [9]:
import sklearn.preprocessing  # 예시 #

In [ ]:
# 패키지에 포함된 메서드 혹은 변수를 사용할 때는 일반 객체와 같이 
# 패키지명.변수 or 패키지명.메서드(매개변수,...)로 사용할 수 있음

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 선택적 임포트
# from 패키지명 import 함수, ...을 사용하여 패키지 내부의 기능을 선택적으로 임포트 할 수 있음

In [12]:
from numpy import arange

In [13]:
arange(5)

array([0, 1, 2, 3, 4])

In [14]:
from numpy import arange as a  # as 사용해서 별칭 지정 가능

In [15]:
a(5)  # 별칭 사용

array([0, 1, 2, 3, 4])

In [ ]:
# 예시 #
from sklearn import * 
# 모든 기능, 패키지 불러오기

# ? 비교
import sklearn
from sklearn import * 
# => 공통 : 전부 불러온다
# => 차이 : (2)간편하게 사용가능 . 내부에서 간략하게 출력가능

# ex) 
import sklearn
# sklearn.base 로 써야하고
from sklearn import * 
# base 만 써도 불러오기 가능 (그러나, 중복이 생길 수 있음을 주의)

# * 와일드 카드로 선택적 임포트를 하게되면 코드사용시 중복된 이름을 사용할 수 있으므로 주의 !!