### <span style='background-color:rgba(100, 50, 0, 0.4);'>넘파이 배열</span>
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모지 차지의 문제를
해결하고자  
수치 해석 프로그램에서는 numpy 라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 c 언어로 구현되어 있어 자료형 지정과 메모리 절약효과를 볼 수 있음

### <span style='background-color:rgba(255, 255, 0, 0.4);'>NumPy import</span>
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함

pip install numpy
numpy 패키지를 프로그램에서 사용하려면 import 해야 함

`import numpy`  
`import numpy as np`

In [57]:
import numpy as np  # 별칭 지정 : numpy -> np

### <span style='background-color:rgba(20, 255, 0, 0.4);'>1차원 배열 만들기</span> 
넘파이의 `array` 함수를 사용하여 리스트를 `ndarray` 타입으로 변경 가능

In [58]:
ndarray_ = np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [59]:
type(ndarray_)

numpy.ndarray

In [60]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [61]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 떄문에 요소에 대한 접근 속도가 빠름

In [62]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [63]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### <span style='background-color:rgba(50, 50, 150, 0.5);'>벡터화 연산</span> 
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터와 연산을 지원

In [64]:
#-- 각 요소를 2씩 곱한 연산 --#

# 리스트를 사용했을 때
numbers = list(range(10))

result = []
for number in numbers:
    result.append(number*2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [65]:
# numpy array 를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2*numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
result = 2*numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [67]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [68]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [69]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [70]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 >2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### <span style='background-color:rgba(20, 255, 0, 0.4);'>2차원 배열</span> 
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()` 의 매개변수로  
전달하면 2차원 배열을 생성할 수 있음

In [71]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
len(numpy_matrix)  # 길이 구하기

3

In [73]:
numpy_matrix[0]  # 특정 요소에 접근

array([1, 2, 3])

In [74]:
len(numpy_matrix[0])

3

### <span style='background-color:rgba(20, 255, 0, 0.4);'>3차원 배열</span> 
리스트의 요소로 2차원 형태를 띄는 리스트를 지정하면 3차원 배열을 만들 수 있음

In [75]:
three_d = [
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]    
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### <span style='background-color:rgba(255, 200, 150, 0.4);'>배열의 차원과 크기 구하기</span> 
'ndim' : 배열의 차원을 정수로 반환
'shape' : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [76]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [77]:
numpy_three_d.ndim , numpy_three_d.shape

(3, (2, 3, 4))

### <span style='background-color:rgba(255, 200, 150, 0.4);'>numpy 배열의 인덱싱</span>
일반적으로 '배열변수[인덱스]' 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게 '배열변수[인덱스,인덱스,...]'의 형태로 사용함  
- 일반 2차원 리스트 : '리스트[인덱스][인덱스]'
- numpy 2차원 배열 : '배열[인덱스,인덱스]'

In [78]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

@ '16'을 찾아보자.

In [79]:
three_d[1]

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

In [80]:
three_d[1][0]

[13, 14, 15, 16]

In [81]:
three_d[1][0][3]

16

In [82]:
# numpy 3차원 배열
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

@ '16'을 찾아보자.

In [83]:
numpy_three_d[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [84]:
numpy_three_d[1,0]

array([13, 14, 15, 16])

In [85]:
numpy_three_d[1,0,3]

16

### <span style='background-color:rgba(255, 200, 150, 0.4);'>numpy 배열 슬라이싱</span>
일반 리스트에서 사용하는 배열 슬라이싱 방법, '리스트[시작인덱스:종료인덱스]'와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 ',' 를 써야하는 것에 주의

In [86]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
numpy_matrix[0, :2]

array([1, 2])

In [90]:
numpy_matrix[:2,0]

array([1, 4])

In [91]:
numpy_matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [92]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [93]:
numpy_three_d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

In [94]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [95]:
# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [96]:
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [97]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [98]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

array([ 7, 12])

In [99]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### <span style='background-color:rgba(50, 50, 255, 100);'>배열 인덱싱</span>
**팬시 인덱싱(fancy indexing)**이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수형태나 슬라이스 형태로 인덱스를 전달하는게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

### 1) <span style='background-color:rgba(20, 200, 150, 0.4);'>불리언 배열 인덱싱</span>
`True`,`False` 두 형태로만 이루어진 배열을 인덱스로 전달하여   
`True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법

불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [100]:
numpy_array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([True,True,False,False,False,True,True,True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [101]:
numpy_array %2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [102]:
numpy_array %2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [103]:
numpy_array[numpy_array %2 == 0]

array([2, 4, 6, 8])

#### <span style='background-color:rgba(20, 200, 150, 0.4);'>정수 배열 인덱싱</span>
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된  
배열을 인덱스로 전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [104]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
index_array = np.array([0,2,3])

In [106]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우  
예외가 발생함

In [107]:
index_array = np.array([0,2,3,6,0,2,3,6,0,2,3,6])

In [108]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

In [109]:
index_array = np.array([0,2,20])

In [110]:
numpy_array[index_array]  # 예외 발생 !!

IndexError: index 20 is out of bounds for axis 0 with size 8

#### <span style='background-color:rgba(20, 200, 150, 0.4);'>다차원 배열에서 배열 인덱싱</span>

In [ ]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [ ]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2,1,0],:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

##### 파이썬으로 다음 연산을 수행하자
다음 행렬과 같은 배열이 있다.  
`x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])`

In [ ]:
# 배열식 만들기
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 1. 배열에서 3의 배수를 찾아라.
x[x %3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# 2. 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x %4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
# 3. 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x %3 == 0) & (x %4 == 1)]

array([9])

### <span style='background-color:rgba(0, 50, 100, 100);'>numpy 배열의 자료형</span>
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음  
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype` 속성으로 확인이 가능

In [ ]:
numpy_array = np.array([1,2,3])
numpy_array.dtype

dtype('int32')

In [ ]:
numpy_array = np.array([1.0,2.0,3.0])
numpy_array.dtype

dtype('float64')

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'])
numpy_array.dtype

dtype('<U3')

`array()` 함수를 사용하여 배열을 생성할 떄 명시적으로 데이터 타입을 지정하지 않으면  
자동으로 데이터 타입을 추론하여 지정하게 됨

만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해주면 됨

##### dtype 의 접두사
b : 불리언  
i : 정수  
f : 실수  
U : 유니코드  

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'],dtype='f')  # dtype을 float으로 명시적 지정해줌
numpy_array.dtype

dtype('float32')

In [111]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

### <span style='background-color:rgba(0, 50, 100, 100);'>numpy 에서 Inf 와 NaN</span>
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf` , 0을 0으로 나누면 `nan` 이 반환됨

### <span style='background-color:rgba(0, 255, 100, 0.5);'>배열 생성</span>
numpy 배열을 생성하는 방법
- `zeros` , `ones`
- `zeros_like` , `once_like`
- `empty`
- `arange`
- `linspace` , `logspace`

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>zeros</span>
크기가 정해져 있는 원소를 0으로 초기화한 배열을 생성하는 함수

In [112]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [115]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2,3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
# dtype 을 명시하여 데이터 타입을 지정할 수 없음
numpy_array = np.zeros((2,3),dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype 으로 문자열 (U)로 지정하게 되면 문자열의 길이가 초과된 부분이 손실됨

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>ones</span>
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수  
`zeros` 함수와 사용법은 동일

In [117]:
ones_array = np.ones((3,2,2), dtype='i') # 정수형 타입
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>zeros_like, ones_like</span>
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [118]:
zeros_array = np.zeros_like(ones_array)  # zeros_like에 ones_array를 전달
zeros_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

In [119]:
zeros_array = np.zeros_like(ones_array,dtype='i')
zeros_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>empty</span> 
크기만 지정하고 원소의 값은 "쓰레기 데이터"로 채워진 배열을 생성  
`zeros` , `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [120]:
empty_array = np.empty((10,10))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95285376e-310, 4.69362364e-322, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554578e-311],
       [1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311],
       [1.06554578e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554578e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311],
       [1.06554553e-311, 1.06554578e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554578e-311,
        1.06554555e-311],
       [1.06554555e-311, 1.06554555e-311, 1.06554555e-311,
        1.06554555e-311, 1.06554555e-311, 1.06554555e-311,
        1.06554578e-311, 1.06554555e-311, 1.06554555e-311,
        1.0

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>arange</span>
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [121]:
arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
arange_array = np.arange(10,50) # 범위 지정 가능
arange_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [123]:
arange_array = np.arange(50,10, -1) # 범위 지정 가능 / -1 역순
arange_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

### <span style='background-color:rgba(0, 50, 100, 100);'>전치 연산</span>
베열의 행과 열의 위치를 전치시키는 방법 - 배열의 `T` 속성으로 반환 받을 수 있음

In [124]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
numpy_matrix.T # 전치 시키기

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [127]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [126]:
numpy_three_d.T # 3차원 전치 시키기

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])