### <span style='background-color:rgba(100, 50, 0, 0.4);'>넘파이 배열</span>
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모지 차지의 문제를
해결하고자  
수치 해석 프로그램에서는 numpy 라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 c 언어로 구현되어 있어 자료형 지정과 메모리 절약효과를 볼 수 있음

### <span style='background-color:rgba(255, 255, 0, 0.4);'>NumPy import</span>
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함

pip install numpy  -> 터미널에 입력해서 확인  
numpy 패키지를 프로그램에서 사용하려면 import 해야 함

`import numpy`  
`import numpy as np`

In [8]:
import numpy as np  # 별칭 지정 : numpy -> np

### <span style='background-color:rgba(20, 255, 0, 0.4);'>1차원 배열 만들기</span> 
넘파이의 `array` 함수를 사용하여 리스트를 `ndarray` 타입으로 변경 가능

In [58]:
ndarray_ = np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [59]:
type(ndarray_)

numpy.ndarray

In [60]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [61]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 떄문에 요소에 대한 접근 속도가 빠름

In [62]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [63]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### <span style='background-color:rgba(50, 50, 150, 0.5);'>벡터화 연산</span> 
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터와 연산을 지원

In [64]:
#-- 각 요소를 2씩 곱한 연산 --#

# 리스트를 사용했을 때
numbers = list(range(10))

result = []
for number in numbers:
    result.append(number*2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [65]:
# numpy array 를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2*numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
result = 2*numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [67]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [68]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [69]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [70]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 >2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### <span style='background-color:rgba(20, 255, 0, 0.4);'>2차원 배열</span> 
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()` 의 매개변수로  
전달하면 2차원 배열을 생성할 수 있음

In [71]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
len(numpy_matrix)  # 길이 구하기

3

In [73]:
numpy_matrix[0]  # 특정 요소에 접근

array([1, 2, 3])

In [74]:
len(numpy_matrix[0])

3

### <span style='background-color:rgba(20, 255, 0, 0.4);'>3차원 배열</span> 
리스트의 요소로 2차원 형태를 띄는 리스트를 지정하면 3차원 배열을 만들 수 있음

In [75]:
three_d = [
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]    
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### <span style='background-color:rgba(255, 200, 150, 0.4);'>배열의 차원과 크기 구하기</span> 
'ndim' : 배열의 차원을 정수로 반환
'shape' : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [76]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [77]:
numpy_three_d.ndim , numpy_three_d.shape

(3, (2, 3, 4))

### <span style='background-color:rgba(255, 200, 150, 0.4);'>numpy 배열의 인덱싱</span>
일반적으로 '배열변수[인덱스]' 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게 '배열변수[인덱스,인덱스,...]'의 형태로 사용함  
- 일반 2차원 리스트 : '리스트[인덱스][인덱스]'
- numpy 2차원 배열 : '배열[인덱스,인덱스]'

In [78]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

@ '16'을 찾아보자.

In [79]:
three_d[1]

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

In [80]:
three_d[1][0]

[13, 14, 15, 16]

In [81]:
three_d[1][0][3]

16

In [82]:
# numpy 3차원 배열
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

@ '16'을 찾아보자.

In [83]:
numpy_three_d[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [84]:
numpy_three_d[1,0]

array([13, 14, 15, 16])

In [85]:
numpy_three_d[1,0,3]

16

### <span style='background-color:rgba(255, 200, 150, 0.4);'>numpy 배열 슬라이싱</span>
일반 리스트에서 사용하는 배열 슬라이싱 방법, '리스트[시작인덱스:종료인덱스]'와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 ',' 를 써야하는 것에 주의

In [86]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
numpy_matrix[0, :2]

array([1, 2])

In [90]:
numpy_matrix[:2,0]

array([1, 4])

In [91]:
numpy_matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [92]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [93]:
numpy_three_d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

In [94]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [95]:
# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [96]:
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [97]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [98]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

array([ 7, 12])

In [99]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### <span style='background-color:rgba(50, 50, 255, 100);'>배열 인덱싱</span>
**팬시 인덱싱(fancy indexing)**이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수형태나 슬라이스 형태로 인덱스를 전달하는게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

### 1) <span style='background-color:rgba(20, 200, 150, 0.4);'>불리언 배열 인덱싱</span>
`True`,`False` 두 형태로만 이루어진 배열을 인덱스로 전달하여   
`True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법

불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [100]:
numpy_array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([True,True,False,False,False,True,True,True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [101]:
numpy_array %2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [102]:
numpy_array %2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [103]:
numpy_array[numpy_array %2 == 0]

array([2, 4, 6, 8])

#### <span style='background-color:rgba(20, 200, 150, 0.4);'>정수 배열 인덱싱</span>
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된  
배열을 인덱스로 전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [104]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
index_array = np.array([0,2,3])

In [106]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우  
예외가 발생함

In [107]:
index_array = np.array([0,2,3,6,0,2,3,6,0,2,3,6])

In [108]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

In [109]:
index_array = np.array([0,2,20])

In [110]:
numpy_array[index_array]  # 예외 발생 !!

IndexError: index 20 is out of bounds for axis 0 with size 8

#### <span style='background-color:rgba(20, 200, 150, 0.4);'>다차원 배열에서 배열 인덱싱</span>

In [ ]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [ ]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2,1,0],:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

##### 파이썬으로 다음 연산을 수행하자
다음 행렬과 같은 배열이 있다.  
`x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])`

In [ ]:
# 배열식 만들기
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 1. 배열에서 3의 배수를 찾아라.
x[x %3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# 2. 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x %4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
# 3. 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x %3 == 0) & (x %4 == 1)]

array([9])

### <span style='background-color:rgba(0, 50, 100, 100);'>numpy 배열의 자료형</span>
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음  
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype` 속성으로 확인이 가능

In [ ]:
numpy_array = np.array([1,2,3])
numpy_array.dtype

dtype('int32')

In [ ]:
numpy_array = np.array([1.0,2.0,3.0])
numpy_array.dtype

dtype('float64')

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'])
numpy_array.dtype

dtype('<U3')

`array()` 함수를 사용하여 배열을 생성할 떄 명시적으로 데이터 타입을 지정하지 않으면  
자동으로 데이터 타입을 추론하여 지정하게 됨

만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해주면 됨

##### dtype 의 접두사
b : 불리언  
i : 정수  
f : 실수  
U : 유니코드  

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'],dtype='f')  # dtype을 float으로 명시적 지정해줌
numpy_array.dtype

dtype('float32')

In [111]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

### <span style='background-color:rgba(0, 50, 100, 100);'>numpy 에서 Inf 와 NaN</span>
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf` , 0을 0으로 나누면 `nan` 이 반환됨

### <span style='background-color:rgba(0, 255, 100, 0.5);'>배열 생성</span>
numpy 배열을 생성하는 방법
- `zeros` , `ones`
- `zeros_like` , `once_like`
- `empty`
- `arange`
- `linspace` , `logspace`

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>zeros</span>
크기가 정해져 있는 원소를 0으로 초기화한 배열을 생성하는 함수

In [112]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [115]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2,3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
# dtype 을 명시하여 데이터 타입을 지정할 수 없음
numpy_array = np.zeros((2,3),dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype 으로 문자열 (U)로 지정하게 되면 문자열의 길이가 초과된 부분이 손실됨

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>ones</span>
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수  
`zeros` 함수와 사용법은 동일

In [117]:
ones_array = np.ones((3,2,2), dtype='i') # 정수형 타입
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>zeros_like, ones_like</span>
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [118]:
zeros_array = np.zeros_like(ones_array)  # zeros_like에 ones_array를 전달
zeros_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

In [119]:
zeros_array = np.zeros_like(ones_array,dtype='i')
zeros_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>empty</span> 
크기만 지정하고 원소의 값은 "쓰레기 데이터"로 채워진 배열을 생성  
`zeros` , `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [120]:
empty_array = np.empty((10,10))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95285376e-310, 4.69362364e-322, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554578e-311],
       [1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311],
       [1.06554578e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554578e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311],
       [1.06554553e-311, 1.06554578e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554553e-311,
        1.06554553e-311, 1.06554553e-311, 1.06554578e-311,
        1.06554555e-311],
       [1.06554555e-311, 1.06554555e-311, 1.06554555e-311,
        1.06554555e-311, 1.06554555e-311, 1.06554555e-311,
        1.06554578e-311, 1.06554555e-311, 1.06554555e-311,
        1.0

#### <span style='background-color:rgba(150, 200, 255, 0.2);'>arange</span>
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [121]:
arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
arange_array = np.arange(10,50) # 범위 지정 가능
arange_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [123]:
arange_array = np.arange(50,10, -1) # 범위 지정 가능 / -1 역순
arange_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

### <span style='background-color:rgba(0, 50, 100, 100);'>전치 연산</span>
베열의 행과 열의 위치를 전치시키는 방법 - 배열의 `T` 속성으로 반환 받을 수 있음

In [124]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
numpy_matrix.T # 전치 시키기

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [127]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [126]:
numpy_three_d.T # 3차원 전치 시키기

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

### <span style='background-color:rgba(0, 50, 100, 100);'>배열의 크기 변경</span>

numpy 배열에서 원소의 개수를 유지한 상태에서 배열의 형태를 변경하려 한다면 `reshape` 메서드를 사용하여 변경할 수 있음

In [2]:
numpy_array = np.zeros(12)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
reshape_array = numpy_array.reshape(4,3) # 4*3 의 형태로 변경해서 출력
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
reshape_array = numpy_array.reshape(2,6) # 2*6 의 형태로 변경해서 출력
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape`메서드에 하나의 인자로 -1 을 넣게 되면  
다른 인자들을 통해서 추론하여 지정

In [5]:
reshape_array = numpy_array.reshape(6,-1) # 6*(2) 의 형태로 변경해서 출력 / -1 이 알아서 2 로 반환해줌
reshape_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
reshape_array = numpy_array.reshape(3,1,-1) # 3*1*(3) 의 형태로 변경해서 출력 / -1 이 알아서 3 로 반환해줌
reshape_array

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [7]:
# 만약 `reshape` 메서드의 인자들의 곱의 결과가 기존 배열의 원소의 총합과 다르면 에러가 발생
# -1 로 지정한 인자가 있을 때, 해당 인자의 곱으로 총합을 계산할 수 없는 경우 - 에러 발생
reshape_array = numpy_array.reshape(5,-1) # 에러
reshape_array

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel` 메서드를 사용

In [8]:
numpy_matrix = np.empty((3,4))
numpy_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
numpy_array = numpy_matrix.flatten() # 1차원 배열로 변경
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
numpy_array = numpy_matrix.ravel() # 1차원 배열로 변경 (동일식)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

배열 사용에서 주의할 점!!  
* (길이가 5 인 1차원 배열) - (5x1 인 2차원 배열) - (1x5 인 2차원 배열)  
    은 서로 각각 다른 배열! (요소의 개수와 내용과 순서가 모두 같더라도, 형태가 다르면 다른 배열)

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis` 속성으로 차원을 증가 시킬 수 있음

In [12]:
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
newaxis_array = numpy_array[np.newaxis] # 한 차원 증가된 식이 출력된다 => 대괄호로 배열이 1개 더 생긴다
newaxis_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
newaxis_array = numpy_array[:,np.newaxis] # 한 차원 증가된 식이 출력된다 / :, - 슬라이싱
newaxis_array

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

### <span style='background-color:rgba(0, 50, 100, 100);'>배열 연결하기</span>

행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결
- `stack` : `dstack` 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결, 단. 연결 축을 개발자가 직접 지정
- `r_` : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결
- `tile` : 하나의 배열을 여러번 반복하여 연결

In [16]:
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones_array = np.ones((3,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
hstack_array = np.hstack([zeros_array, ones_array]) # 행이 같은 두 식 => hstack => 행에 열을 붙여서 새로운 배열 생성
hstack_array

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

========================================

In [19]:
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
ones_array = np.ones((2,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
vstack_array = np.vstack([zeros_array, ones_array]) # 열이 같은 두 식 => vstack => 열에 행을 붙여서 새로운 배열 생성
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

=======================================

In [22]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
ones_array = np.ones((3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
dstack_array = np.dstack([zeros_array, ones_array]) # 요소 값을 배열로 바꿔서 출력
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

===============================================

In [25]:
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [26]:
stack_array = np.stack([zeros_array,ones_array])
stack_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
stack_array = np.stack([zeros_array,ones_array], axis = 2)
stack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [34]:
stack_array.shape

(3, 3, 2)

==================================================

In [35]:
r_array = np.r_[zeros_array,ones_array] # 3*3 의 형태를 6*3 으로 변경해줌
r_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

===================================================

In [36]:
c_array = np.c_[zeros_array, ones_array]
c_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [37]:
# +) PLUS 응용 수식
c_array = np.c_[np.zeros(3),np.zeros(3)]
c_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

===================================================

In [39]:
tile_array = np.tile(zeros_array, 2) # zeros_array 내용을 2번 반복한다.
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

=============================================

In [ ]:
# 예제) 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.

# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

# ? 반복되는 형태 

In [46]:
# [0, 0, 0, 1, 1] 만들기
zeros_array = np.zeros((3,3))
ones_array = np.ones((3,2))
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [48]:
# [0, 0, 0, 1, 1] 만들기
zeros_array = np.zeros((3,3))
ones_array = np.ones((3,2))
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [49]:
# [ 10.,   20.,   30.,   40.,   50.] ... [.. 140., 150.] 만들기
arange_array = np.arange(10,151,10)
arange_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [50]:
# 3*5로 배열 바꾸기
reshape_array = arange_array.reshape(3,5)
reshape_array 

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [51]:
# 합치기
vstack_array = np.vstack([hstack_array, reshape_array])
vstack_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [52]:
# 동일하게 2회 반복 출력 => 결과값
tile_array = np.tile(vstack_array, (2,1))
tile_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### <span style='background-color:rgba(0, 50, 100, 100);'>2차원 그리드 포인트 생성</span>

좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [53]:
x = np.arange(3)
x

array([0, 1, 2])

In [54]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [56]:
X,Y = np.meshgrid(x,y)  # x축에 대한 좌표값
X,Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [60]:
[list(zip(x,y))for x,y in zip(X,Y)]  # x축에 대한 좌표값

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [62]:
list(zip(X,Y))  #안에 값들 하나씩 꺼내와서 list 로 정리

[(array([0, 1, 2]), array([0, 0, 0])),
 (array([0, 1, 2]), array([1, 1, 1])),
 (array([0, 1, 2]), array([2, 2, 2])),
 (array([0, 1, 2]), array([3, 3, 3])),
 (array([0, 1, 2]), array([4, 4, 4]))]

### <span style='background-color:rgba(0, 50, 100, 100);'>벡터화 연산</span>

numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음

In [85]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [96]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
    z[index] = z[index] + y[index]

CPU times: total: 15.6 ms
Wall time: 2.99 ms


In [92]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [97]:
x = np.arange(5)
y = np.arange(10,15)
z = np.arange(5)

In [98]:
np.all(x == y)

False

In [99]:
np.all(x == z)

True

In [100]:
np.all(x <= y)

True

============================================

In [101]:
x

array([0, 1, 2, 3, 4])

In [104]:
10 * x 

array([ 0, 10, 20, 30, 40])

In [105]:
10 ** x 

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [106]:
x ** 10

array([      0,       1,    1024,   59049, 1048576], dtype=int32)

### <span style='background-color:rgba(0, 50, 100, 100);'>브로드 캐스팅</span>

차원이 서로 다른 배열을 연산하는 기능, 부족한 차원에 대하여 반복 확장하여 큰 배열의 크기에 맞춘 후 연산을 진행

In [108]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [109]:
x + 1 #각각의 수에 +1씩 하여 연산이 된다

array([1, 2, 3, 4, 5])

In [110]:
# 2차원으로 만들기
x = np.arange(15)
x = x.reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [112]:
x + y

# array([[ 0,  1,  2,  3,  4],      array([[0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],             [0,  1,  2,  3,  4],  
#        [10, 11, 12, 13, 14]])            [0,  1,  2,  3,  4]])  

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

### <span style='background-color:rgba(0, 50, 100, 100);'>차원 축소 연산</span>

배열의 하나의 행을 하나의 집합으로 보고 그 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [115]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
x.max()

9

In [118]:
x.min()

0

In [119]:
x.mean() #평균값

4.5

In [120]:
x.sum(axis=0)  #array([[0, 1, 2, 3, 4],
               #      [5, 6, 7, 8, 9]])   0+5 , 1+6 , 2+7 , 3+8 , 4+9

array([ 5,  7,  9, 11, 13])

In [122]:
x.sum(axis=1)  #array([[0, 1, 2, 3, 4],   0+1+2+3+4
               #      [5, 6, 7, 8, 9]])   5+6+7+8+9

array([10, 35])

### <span style='background-color:rgba(0, 50, 100, 100);'>정렬</span>

`sort` 메서드로 배열을 정렬 할 수 있음  

`axis` 매개변수로 정렬 기준을 정할 수 있음  
`axis=0` : 행을 따로 분리하여 정렬  
`axis=1` : 열을 따로 분리하여 정렬  
`axis`를 지정하지 않으면 가장 나중 차원을 기준으로 정렬  

In [144]:
x = np.array(
    [[5,2,7,4],
    [11,8,6,5],
    [8,5,11,2]])
x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  5],
       [ 8,  5, 11,  2]])

In [141]:
x.sort()
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [143]:
x.sort(axis=0)  #행 정렬 ↓
x

array([[ 5,  2,  6,  2],
       [ 8,  5,  7,  4],
       [11,  8, 11,  5]])

In [145]:
x.sort(axis=1)  #열 정렬 →
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [133]:
np.argsort(x)  #[]를 정렬했을 때의 인덱스을 나타낸다

array([[1, 3, 0, 2],
       [3, 2, 1, 0],
       [3, 1, 0, 2]], dtype=int64)

==================================================

<span style='background-color:rgba(255, 150, 100, 0.5);'>예제) 넘파이로 다음 연산을 수행한다</span>

실수로 이루어진 3 x 3 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

1. 전체의 최댓값 
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값


In [149]:
x = np.array(
    [[34,4,1],
    [1,78,23],
    [6,19,2]])
x

array([[34,  4,  1],
       [ 1, 78, 23],
       [ 6, 19,  2]])

In [135]:
# 1. 전체의 최댓값 
x.max()

78

In [151]:
# 2. 각 행의 합
x.sum(axis=1)

array([ 39, 102,  27])

In [137]:
# 3. 각 행의 최댓값
x.max(axis=1)

array([34, 78, 19])

In [138]:
# 4. 각 열의 평균
x.mean(axis=0)

array([13.66666667, 33.66666667,  8.66666667])

In [139]:
# 5. 각 열의 최솟값
x.min(axis=0)

array([1, 4, 1])

### <span style='background-color:rgba(0, 50, 100, 100);'>Numpy 배열 통계 연산</span>

- 데이터 개수 구하기 : `len()` 내장 함수
- 표본 평균 : `mean()` 메서드
- 표본 분산 : `var()` 메서드
- 표본 표준편차 : `std()` 메서드
- 최대, 최소 : `max()` , `min()` 메서드
- 중앙값 : `median()` 메서드
- 사분위수 : `percentile()` 메서드

In [2]:
samples = np.array([9,2,4,20,24,2,23,92,24,-23])
samples

array([  9,   2,   4,  20,  24,   2,  23,  92,  24, -23])

In [3]:
sample_volume = len(samples) 
sample_volume
#개수 구하기

10

In [4]:
sample_mean = samples.mean()
sample_mean
#평균 구하기
    # 같은 식 #
sample_mean = np.mean(samples)
sample_mean

17.7

In [7]:
sample_variance = samples.var()
sample_variance
#분산 구하기
    # 같은 식 #
sample_variance = np.var(samples)
sample_variance

804.61

In [10]:
sample_standard = samples.std()
sample_standard
#표준편차 구하기
    # 같은 식 #
sample_standard = np.std(samples)
sample_standard

28.365648238670662

In [11]:
sample_max = samples.max()
sample_max
#최대값 구하기

92

In [13]:
sample_min = samples.min()
sample_min
#최소값 구하기

-23

In [15]:
sample_median = np.median(samples)
sample_median
#중간값 구하기  ... +) np에만 기능 탑재 / 객체 X

14.5

In [16]:
sample_0per = np.percentile(samples, 0)
sample_0per
#사분위수 구하기

-23.0

In [18]:
sample_25per = np.percentile(samples, )
sample_25per
#사분위수 구하기 - 25% 의 값

2.5

In [19]:
sample_50per = np.percentile(samples, 50)
sample_50per
#사분위수 구하기 - 50%의 값 = median 값과 동일

14.5

In [20]:
sample_75per = np.percentile(samples, 75)
sample_75per
#사분위수 구하기 - 75% 값

23.75

In [21]:
sample_100per = np.percentile(samples, 100)
sample_100per
#사분위수 구하기 - 100% 값 = 최대값

92.0

### <span style='background-color:rgba(0, 50, 100, 100);'>난수 생성에 필요한 시드 설정</span>


numpy() 패키지에 있는 `seed()` 메서드에 매개변수로 난수 생성시 필요한 시드를 설정 함

In [22]:
np.random.seed(10)

In [23]:
random_array = np.random.rand(10)
random_array

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

### <span style='background-color:rgba(0, 50, 100, 100);'>데이터 순서 임의로 바꾸기</span>

numpy 패키지의 random 하위 패키지의 `shuffle()` 메서드로 배열을 임의 순서로 변경 가능(자체 변환)

In [25]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(range_array) 
range_array
# 데이터 순서 임의로 바꾸기 

array([8, 4, 7, 5, 0, 3, 9, 1, 2, 6])

In [31]:
np.random.shuffle(range_array) 
range_array
# "임의로" 이기 때문에 할 때 마다 다른 값이 나옴

array([1, 5, 3, 6, 2, 9, 8, 7, 0, 4])

### <span style='background-color:rgba(0, 50, 100, 100);'>데이터 샘플링</span>

모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는 방법  
numpy 패키지의 random 하위 패키지의   
`choice(모집단배열, 표본크기, 중복선택여부,각요소의선택확률배열)`메서드로 사용가능

In [32]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
sample_array = np.random.choice(population_array, 5)
sample_array
#choice(모집단배열, 표본크기) 로 출력

array([8, 8, 6, 6, 5])

In [68]:
sample_array = np.random.choice(population_array, 5, replace=False)
sample_array
#중복을 허용하지 않고 5개 출력

array([4, 1, 3, 7, 9])

In [74]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
sample_array = np.random.choice(population_array, 10000, p=probability_array)
sample_array

array([9, 5, 4, ..., 7, 9, 5])

In [71]:
sample_array = np.random.choice(population_array, 12, replace=False)
sample_array

ValueError: Cannot take a larger sample than population when 'replace=False'

In [72]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.25]
sample_array = np.random.choice(population_array, 10000, p=probability_array)
sample_array

ValueError: 'a' and 'p' must have same size

### 난수 배열 생성
- `rand()` : 0과 1사이의 균일 분포를 따르는 난수 배열 생성
- `randn()` : 표준 정규 분포를 따르는 난수 배열 생성
- `randint(low, high=정수, size=정수혹은튜플)` : 지정한 범위 정수의 균일 분포를 따르는 난수 배열 생성

In [42]:
rand_array = np.random.rand(10)
rand_array

array([0.25137413, 0.59737165, 0.90283176, 0.53455795, 0.59020136,
       0.03928177, 0.35718176, 0.07961309, 0.30545992, 0.33071931])

In [43]:
randn_array = np.random.randn(10)
randn_array

array([-1.79857302, -0.68520734, -1.40986887,  1.25239859,  0.46956276,
        0.32692165,  1.80854321, -1.413068  ,  2.52330509,  0.3473178 ])

In [52]:
randint_array = np.random.randint(10)
randint_array
# 0-9 까지의 랜덤 수 하나 출력

3

In [53]:
randint_array = np.random.randint(10, size=10)
randint_array
# 랜덤 수 10개 출력

array([2, 6, 0, 5, 1, 3, 6, 5, 5, 1])

In [57]:
randint_array = np.random.randint(10, high=20, size=10)
randint_array
# 최대 20까지 중 랜덤 10개 출력

array([16, 13, 14, 15, 14, 10, 12, 18, 10, 17])

In [55]:
randint_array = np.random.randint(10, high=20, size=(3,5))
randint_array

array([[19, 19, 11, 15, 19],
       [11, 14, 17, 17, 17],
       [19, 17, 16, 10, 13]])

### 정수 데이터 카운팅

배열의 요소가 정수이면 `unique()` 메서드나 `bincount()` 메서드로 간단하게 분석할 수 있음

In [76]:
analysis_array = np.unique(sample_array)
analysis_array

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [79]:
analysis_arary = np.unique(sample_array, return_counts=True)
analysis_array

array([1001,  478,  456,    0, 1564, 2521,  995,  475,  479, 2031],
      dtype=int64)

In [78]:
analysis_array = np.bincount(sample_array, minlength=10)
analysis_array

array([1001,  478,  456,    0, 1564, 2521,  995,  475,  479, 2031],
      dtype=int64)

================================예제 문제=============================

In [9]:
# 1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
coin_simulation = np.random.randint(2, size=10)
coin_simulation

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1])

In [16]:
# 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
dice_simulation = np.random.randint(1, high=7 , size=100)
dice_simulation_mean = np.mean(dice_simulation)
dice_simulation_mean

3.32

In [20]:
# 가격이 10,000원인 주식이 있다. 
# 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 
# 250일 동안의 주가를 무작위로 생성하라

money = 10000

variation_ranges = (np.random.randn(250) / 100) + 1
stock_money = [] #가독성을 위한 빈리스트 만들기 / 결과를 담는다

for ratio in variation_ranges: #반복 돌리는 작업 - 주가를 계산하는 법 : 전날 주가에서 +/- 되기 때문에
    money = round(money * round(ratio,4)) #round 사용으로 소수점 4자리까지만 사용한다
    stock_money.append(money)

stock_money_array = np.array(stock_money) #방대한 양의 데이터를 배열로 정리
stock_money_array

array([ 9742,  9734,  9752,  9728,  9655,  9745,  9918,  9772,  9801,
        9775,  9841,  9711,  9711,  9737,  9642,  9647,  9587,  9439,
        9582,  9624,  9558,  9618,  9600,  9448,  9405,  9363,  9320,
        9280,  9163,  9270,  9164,  9115,  8948,  8995,  8907,  8854,
        8825,  8767,  8697,  8790,  8597,  8496,  8416,  8376,  8425,
        8415,  8407,  8283,  8245,  8218,  8250,  8248,  8282,  8146,
        8153,  8180,  8209,  8150,  8172,  8150,  8103,  7985,  7924,
        7886,  7817,  7832,  7928,  7982,  7885,  7752,  7852,  7813,
        7940,  8096,  7961,  7877,  7977,  8045,  8183,  8155,  8113,
        8119,  8172,  8229,  8354,  8545,  8551,  8554,  8587,  8681,
        8788,  8684,  8688,  8763,  8906,  8830,  8975,  8984,  9008,
        9046,  9170,  9054,  9081,  9150,  9228,  9233,  9237,  9283,
        9465,  9543,  9582,  9654,  9698,  9703,  9604,  9658,  9715,
        9636,  9545,  9583,  9547,  9723,  9713,  9686,  9780,  9669,
        9852,  9893,