### 넘파이 배열
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모지 차지의 문제를
해결하고자  
수치 해석 프로그램에서는 numpy 라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 c 언어로 구현되어 있어 자료형 지정과 메모리 절약효과를 볼 수 있음

### NumPy import
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함

pip install numpy
numpy 패키지를 프로그램에서 사용하려면 import 해야 함

import numpy  
import numpy as np

In [2]:
import numpy as np

### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능

In [3]:
ndarray_ = np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [4]:
type(ndarray_)

numpy.ndarray

In [5]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [6]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 떄문에 요소에 대한 접근 속도가 빠름

In [7]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [8]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터와 연산을 지원

In [12]:
#-- 각 요소를 2씩 곱한 연산 --#

# 리스트를 사용했을 때
numbers = list(range(10))

result = []
for number in numbers:
    result.append(number*2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
# numpy array 를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2*numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
result = 2*numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [15]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [16]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [17]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [22]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 >2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 "array()" 의 매개변수로  
전달하면 2차원 배열을 생성할 수 있음

In [23]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
len(numpy_matrix)  # 길이 구하기

3

In [25]:
numpy_matrix[0]  # 특정 요소에 접근

array([1, 2, 3])

In [26]:
len(numpy_matrix[0])

3

### 3차원 배열
리스트의 요소로 2차원 형태를 띄는 리스트를 지정하면 3차원 배열을 만들 수 있음

In [28]:
three_d = [
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]    
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])